plugins {
    id 'com.android.application'
}

android {
    namespace 'com.daosheng.selenelivetv'
    compileSdk 36

    defaultConfig {
        applicationId 'com.daosheng.selenelivetv'
        minSdk 28
        targetSdk 35
        versionCode 14
        versionName '1.4.8-android9-bundled-fallback'
        ndk { abiFilters 'armeabi-v7a' }
    }
}

dependencies {
    implementation 'dev.jdtech.mpv:libmpv:1.0.0'
}
